### ISSUE TITLE
openni_saver build fails.

### ISSUE THREAD

**Issue by cdondrup** [strands-project/data_compression#14]
Just updated my stable installation and tried to build it:

```
CMake Error at data_compression/openni_saver/CMakeLists.txt:78 (add_executable):
  Cannot find source file:

    src/synch_saver_node.cpp
```

**Comment by nilsbore** [comment]
Probably forgot to add that file. Will update soon. Thanks!

**Comment by nilsbore** [comment]
Solved by https://github.com/strands-project/data_compression/pull/15, closing.
