### ISSUE TITLE
Jenkins reported broken build

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/data_compression#27]
with the following problem:

```
In file included from <http://marcs-pc:8080/job/catkin_make_strands_desktop_full/ws/catkin_ws/src/data_compression/openni_saver/src/cv_saver.cpp>:1:0:
<http://marcs-pc:8080/job/catkin_make_strands_desktop_full/ws/catkin_ws/src/data_compression/openni_saver/src/cv_saver.h>:8:45: fatal error: openni_saver/StartStopRecording.h: No such file or directory
compilation terminated.
```

Please assign somebody to fix this problem or close this issue if it's already fixed.

**Comment by nilsbore** [comment]
I'll get on it.

**Comment by nilsbore** [comment]
This should be solved by https://github.com/strands-project/data_compression/pull/28, closing. Btw, seems to be a good idea to compile with option e.g. -j3 to check that the dependencies aren't wrong. Closing.
