### ISSUE TITLE
Hydro compile

### ISSUE THREAD

**Issue by cburbridge** [strands-project/data_compression#39]
Trying to compile a strands install using the Hydro instructions on a fresh install of Ubuntu 12.04, I get this error:

```
[  9%] Building CXX object data_compression/openni_saver/CMakeFiles/openni_image_saver.dir/src/openni_image_saver.cpp.o
In file included from /opt/strands/strands_catkin_ws/src/data_compression/openni_saver/src/openni_image_saver.cpp:1:0:
/opt/strands/strands_catkin_ws/src/data_compression/openni_saver/src/openni_image_saver.h:7:41: fatal error: openni_saver/LoggingService.h: No such file or directory
compilation terminated.
make[2]: *** [data_compression/openni_saver/CMakeFiles/openni_image_saver.dir/src/openni_image_saver.cpp.o] Error 1
make[1]: *** [data_compression/openni_saver/CMakeFiles/openni_image_saver.dir/all] Error 2
make: *** [all] Error 2
Invoking "make" failed
```

Not 100% sure it is specifically because of the hydro change...

**Comment by nilsbore** [comment]
Hi, I can't fix this atm but I'll have a look at it as soon as I get home next Monday. Greetings from the Himalayas:)

**Comment by nilsbore** [comment]
Hey, I couldn't replicate this myself but I found a typo that could be the cause of your problem. Can you please try to compile the hydro-devel branch from my repo: https://github.com/nilsbore/data_compression.git

**Comment by nilsbore** [comment]
This can be closed now.
