### ISSUE TITLE
Remove repo ahead of release

### ISSUE THREAD

**Issue by nilsbore** [strands-project/data_compression#42]
This package is pretty outdated and has not been used. The idea was to be able to compress rosbags more efficiently but with this technique only one camera is supported. At KTH we are currently only doing observations at waypoints and then uploading it to an ftp server. Since the plan otherwise is to trigger complete data collection when needed, I propose to delete this repo since heavy refactoring is needed to get it to do what we want. If needed, my repo can later be merged into a new project.

Your thoughts, @hawesie , @marc-hanheide ?

**Comment by marc-hanheide** [comment]
I think we shouldn't loose it. Not all repositories need to be released. So, if it's not fit for release, I'd say keep it but don't release it...

**Comment by nilsbore** [comment]
Allright.
