### ISSUE TITLE
[catkinized_libav] Add proper install targets

### ISSUE THREAD

**Issue by nilsbore** [strands-project/data_compression#44]
I'm working on installing catkinized_libav correctly (enabling catkin_make install). I am then copying the include folders and library files to the correct directories in the Cmake file:

https://github.com/nilsbore/data_compression/blob/hydro-devel/catkinized_libav/CMakeLists.txt

But I can't figure out how to also copy the symlinks, or rather the solutions seem overly complicated. Is there any more correct way of doing this? @marc-hanheide , @cdondrup ?

**Comment by nilsbore** [comment]
If this is sorted out and tested by a few people I think we can release this repository since it has no dependencies elsewhere in the project.

**Comment by cdondrup** [comment]
No idea really... What kind of symlinks are we talking about and what is the exact problem?

**Comment by marc-hanheide** [comment]
Easy... in install, all you need to do is append `/.` to the symlink (if it's a directory) and it will be resolved.

**Comment by marc-hanheide** [comment]
that's what I did in https://github.com/strands-project/twitter_bootstrap/commit/43fefa4d098cbb35b32d4dde658abd2b43538fcd

**Comment by nilsbore** [comment]
Thanks, this worked! Couldn't find any information on this!

**Comment by nilsbore** [comment]
The problem now is that the shared libraries are linking to the ones that were situated in the folder from where I installed them, i.e. the /devel/lib ones. Do you know a way to fix this?

**Comment by nilsbore** [comment]
It could have something to do with that I'm installing them separately, one by one.

**Comment by marc-hanheide** [comment]
@nilsbore what's the plan about releasing this?

**Comment by nilsbore** [comment]
The plan was to release it, everything should be set up.

**Comment by marc-hanheide** [comment]
on it!

**Comment by nilsbore** [comment]
@marc-hanheide Cool!

**Comment by marc-hanheide** [comment]
it worked, but there are many deprecation warnings in https://lcas.lincoln.ac.uk/jenkins/job/ros-hydro-catkinized-libav_binarydeb_precise_amd64/1/

nothing to worry about... (but a little annoying because destroy my nice picture of no build failing :smile: )

**Comment by nilsbore** [comment]
This might indicate a problem though. Is it possible to check which libav
library libav_image_transport links against?
Den 15 nov 2014 01:01 skrev "Marc Hanheide" notifications@github.com:

**Comment by nilsbore** [comment]
Or I'll first see if it gives the same warnings on my system
Den 15 nov 2014 08:47 skrev "Nils Bore" nilsbore@gmail.com:

**Comment by nilsbore** [comment]
I'm also getting these warnings so it seems to be an issue with that version of libav. So yeah, lets ignore it for now=).
