### ISSUE TITLE
[libav_image_transport] apt-get install not linking catkinized_libav

### ISSUE THREAD

**Issue by nilsbore** [strands-project/data_compression#52]
When I install the `libav_image_transport` on the robot via `apt-get`, it crashes because `/opt/ros/hydro/lib/libav_image_transport` is not linking any `catkinized_libav` libraries. However, when I install it by first downloading, compiling and installing the package, it works fine, everything links correctly. This is also true on my computer. Also on both mine and Rares' machine, the apt-get package actually works. But on Rares' machine `/opt/ros/hydro/lib/libav_image_transport` does NOT seem to be linking the libraries. @marc-hanheide Do you have any idea what might be going on?

**Comment by marc-hanheide** [comment]
No, I don't get this... Is libav_image_transport your code? And why would it be linking when installed via apt-get?

**Comment by nilsbore** [comment]
Yes, or I've done the linking part in there. I mean the library that I install via apt-get should link the libav libraries also installed via apt-get (when checked via `ldd /hydro/lib/liblibav_image_transport.so`). That it doesn't seem to be the problem on the robot. It fails because of: `/opt/ros/hydro/lib/image_transport/republish: symbol lookup error: /opt/ros/hydro/lib//liblibav_image_transport.so: undefined symbol: avcodec_register_all`.

**Comment by nilsbore** [comment]
That function should be part of the `libavcodec` library which is correctly installed in `/opt/ros/hydro/lib/`

**Comment by nilsbore** [comment]
The strange thing as that it is working on both my and Rares' machine but not on the robot...

**Comment by nilsbore** [comment]
Ok, hold on, that last part might not hold.

**Comment by marc-hanheide** [comment]
does it load things dynamically, probably?

**Comment by marc-hanheide** [comment]
I mean using dl_load

**Comment by nilsbore** [comment]
I discovered that you need to have a camera stream before the node actually crashes. So the common denominator between all computers is that the apt-get does not work, but `catkin_make install && rm -rf build devel && source install.setup.bash` and run works.

**Comment by nilsbore** [comment]
Eh, now you're speaking past me=).

**Comment by nilsbore** [comment]
The `image_transport republish` loads the library dynamically if that's what you mean. Using pluginlib I think.

**Comment by marc-hanheide** [comment]
nevermind... but what the .... yes, that's what I mean. I can't really see why that should be different. Hmmmm. I'll try to think a bit more in a bit

**Comment by nilsbore** [comment]
You can try it by running e.g. `rosrun image_transport republish raw in:=/head_xtion/depth/image_raw libav out:=/toes`, given that you have a camera feed.

**Comment by marc-hanheide** [comment]
hmmm, doesn't complain for me

**Comment by nilsbore** [comment]
Do you have a camera publishing on the in topic?

**Comment by marc-hanheide** [comment]
ah. nope...

**Comment by nilsbore** [comment]
I can supply you with a rosbag tomorrow if you want to try. It didn't work on the two machines where I had a camera.

**Comment by marc-hanheide** [comment]
got it working... and failing

**Comment by marc-hanheide** [comment]
the problem is that all libraries are stripped of the symbols... so `dlopen` calls like in pluginlib are probably not supported that easily... 

```
$ nm -C /opt/ros/hydro/lib//liblibav_image_transport.so
nm: /opt/ros/hydro/lib//liblibav_image_transport.so: no symbols
```

I'll investigate

**Comment by nilsbore** [comment]
Ok, cool.

**Comment by nilsbore** [comment]
Are you sure that is not that the libraries are not linked correctly? The library `liblibav_image_transport` should link e.g. `libavcodec` and `libavutil`, which show up when I do `ldd liblibav_image_transport.so` on my locally compiled installed system. The apt-get library does not show them when I check with ldd however.

**Comment by marc-hanheide** [comment]
hmm.... you're probably right...

**Comment by marc-hanheide** [comment]
I'm still new to this debian stuff... I don't know for sure what's going on here. TBH

**Comment by marc-hanheide** [comment]
I have made a fix to avoid stripping that lib. Stripping can also include removing unnecessary links, so maybe it makes a difference...

**Comment by nilsbore** [comment]
Fingers crossed!

**Comment by marc-hanheide** [comment]
didn't work... It's got symbols now, but still not the link to the other file

**Comment by marc-hanheide** [comment]
no idea really, sorry. And I have to call it day now. Pretty knackered.

**Comment by nilsbore** [comment]
Hmm... I've done a little bit of research. First, to explain the setup: `catkinized_libav` exports a library through catkin, `libav_wrap`, that links all of the libraries in libav:
https://github.com/strands-project/data_compression/blob/hydro-devel/catkinized_libav/CMakeLists.txt#L43
`libav_image_transport` then depends on that catkin project and links `libav_wrap` through `${catkin_LIBRARIES}`:
https://github.com/strands-project/data_compression/blob/hydro-devel/libav_image_transport/CMakeLists.txt#L9
This seems to make `libav_image_transport` link the libav libraries when you install it on your own system.

I also found a line it the CMake that could have something to do with this:
https://github.com/strands-project/data_compression/blob/hydro-devel/libav_image_transport/CMakeLists.txt#L147
and a thread on an issue that could be related:
https://github.com/ros-perception/perception_pcl/issues/9

**Comment by nilsbore** [comment]
Maybe we should try to just remove that line?

**Comment by marc-hanheide** [comment]
Could try... though I really don't understand the consequences. That command seems magic...

**Comment by nilsbore** [comment]
TBH, me neither. It's in the original package though.

**Comment by marc-hanheide** [comment]
I just checked the last build log: https://lcas.lincoln.ac.uk/jenkins/job/ros-hydro-libav-image-transport_binarydeb_precise_amd64/4/console Nothing obvious in there that looks different to what you would do on your own machine.

**Comment by nilsbore** [comment]
Have you tried building and installing on yours? Shouldn't be necessary though since it worked on two other machines=P. I'll try removing the line and check what happens when I build locally.

**Comment by nilsbore** [comment]
Yeah, it's still working so maybe it's worth a try. Did you already do it or should I supply a patch?

**Comment by marc-hanheide** [comment]
I didn't do anything. give it a shot and let me know to re-release.

**Comment by nilsbore** [comment]
Ok, merged: https://github.com/strands-project/data_compression/pull/54. Please try again.

**Comment by nilsbore** [comment]
No luck there...=(

**Comment by nilsbore** [comment]
EDIT: Forget this, will try again
Ok @marc-hanheide , so you reported `make[4]: *** No rule to make target devel/lib/libavcodec.so, needed by devel/lib/liblibav_image_transport.so. Stop.` from the build farm. This does not happen on my system. Does this mean that the files required by `libav_image_transport` at https://github.com/strands-project/data_compression/blob/hydro-devel/libav_image_transport/CMakeLists.txt#L155 do not exist in the build server when this is compiled? They do exist after installing with apt-get in `/opt/ros/hydro/lib`. Or is it faulty to define it this way? It seems to work for `libav_wrap`:  https://github.com/strands-project/data_compression/blob/hydro-devel/catkinized_libav/CMakeLists.txt#L40 which compiles on the build farm.

**Comment by nilsbore** [comment]
I think I messed things up in that attempt, will try a new one.

**Comment by marc-hanheide** [comment]
Yes, the problem is that it expects that lib in the devel space: `devel/lib/libavcodec.so` and it certainly does not exist in there.

**Comment by nilsbore** [comment]
Yeah, exactly=). Will change that now.

**Comment by nilsbore** [comment]
But on the build farm, `/opt/ros/hydro/lib` should be in `LD_LIBRARY_PATH` right? So there shouldn't be any need of prefixing the path?

**Comment by nilsbore** [comment]
So I'm beginning to see what the problem might be. There is one difference when building on the build farm vs locally. I'm guessing that on the build farm, the package catkinized_libav is built for itself and then installed. That installed library is then used to build libav_image_transport. Locally I build the packages together, so libav_image_transport uses the catkinized_libav in devel for building and linking. These are then installed together. Gonna try to verify that this is the problem.

**Comment by nilsbore** [comment]
Good news! This was it! Now I just gotta figure out how to solve it!

**Comment by marc-hanheide** [comment]
Yes, that is the difference! But I still don't see what the problem is...

**Comment by nilsbore** [comment]
https://github.com/strands-project/data_compression/pull/57 should fix it, works on my machine at least.

**Comment by marc-hanheide** [comment]
See https://lcas.lincoln.ac.uk/jenkins/job/pr-hydro-data_compression/11/console

Sorry I'm mostly offline tonight...

**Comment by nilsbore** [comment]
Wow, that's pretty devastating=(. This works fine on my machine when I first compile and install `catkinized_libav` and then compile `libav_image_transport` using the installed library. I don't understand the error message... Shouldn't it try to compile `catkinized_libav` (which is a dependency of `libav_image_transport`) before trying to read its libraries? Anyways, I'm going to bed now, see you tomorrow.

**Comment by nilsbore** [comment]
Specifically, I'm confused about the help offered:

```
CMake Error at /tmp/test_repositories/build_repository/devel/share/catkinized_libav/cmake/catkinized_libavConfig.cmake:141 (message):
  Project 'libav_image_transport' tried to find library 'avdevice'.  The
  library is neither a target nor built/installed properly.  Did you compile
  project 'catkinized_libav'? Did you find_package() it before the
  subdirectory containing its code is included?
```

In the log, I don't see `catkinized_libav` being built, which it should, since I did indeed find_package() it.

**Comment by nilsbore** [comment]
Is there any way to give me temporary access to trigger re-releases of data
compression?
Den 22 nov 2014 00:00 skrev "Marc Hanheide" notifications@github.com:

**Comment by marc-hanheide** [comment]
see private email!

**Comment by nilsbore** [comment]
Happy to close this now...
