### ISSUE TITLE
specifing the date when replaying a recorded video

### ISSUE THREAD

**Issue by vonovak** [strands-project/data_compression#59]
When using the `mongodb_play.py` utility to replay the rgb and depth topics, is it possible to specify date (datetime) from which the playback should start?
Thanks

**Comment by nilsbore** [comment]
That is not supported at the moment, AFAIK. @hawesie has done something similar before though:

``` python
def mkdatetime(date_string):
    return datetime.strptime(date_string, '%d/%m/%y %H:%M')

if __name__ == "__main__":
    rospy.init_node("schedule_replay")

    parser = argparse.ArgumentParser(description='Replays saved scheduling problems from mongodb_store.')

    parser.add_argument('start', metavar='S', type=mkdatetime, nargs='?', default=datetime.utcfromtimestamp(0),
                   help='start datetime of query, defaults to no start. Formatted "d/m/y H:M" e.g. "06/07/14 06:38"')

    parser.add_argument('end', metavar='E', type=mkdatetime, nargs='?', default=datetime.utcnow(),
                   help='end datetime of query, defaults to now. Formatted "d/m/y H:M" e.g. "06/07/14 06:38"')


    args = parser.parse_args()



    msg_store = MessageStoreProxy(collection='scheduling_problems')
    meta_query = {}
    meta_query["inserted_at"] = {"$gte": args.start, "$lte" : args.end} 

    scheduling_problems = msg_store.query(StringPairList._type, meta_query=meta_query)
```

from https://github.com/strands-project/strands_executive/blob/hydro-devel/scheduler/scripts/replay_scheduling_problems.py
But you need to use the command line args to set these: https://github.com/strands-project/mongodb_store/blob/hydro-devel/mongodb_store/scripts/mongodb_play.py#L284

Hope this helps.

**Comment by nilsbore** [comment]
Closing, please file a request with https://github.com/strands-project/mongodb_store instead, @vonovak .
